services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ollytiket
      POSTGRES_PASSWORD: ollytiket
      POSTGRES_DB: ollytiket
    ports:
      - '5432:5432'
    volumes:
      - ollytiket-db:/var/lib/postgresql/data

volumes:
  ollytiket-db:
